### ISSUE TITLE
1.4.1 crash

### ISSUE THREAD

**Issue by PaulWoitaschek** [outfoxx/swiftpoet#65]
SwiftPoet 1.4.1 causes this crash. As the code base is very complex and I can't toString the FileSpec I can't easily share a reproducer, but from the stacktrace it's pretty clear what happens.
This worked fine in 1.4.0 and is caused by this change: 6da6707818e10677c3738b9dbe8435572eb15e5c

```kotlin
Caused by: java.lang.IndexOutOfBoundsException: Empty list doesn't contain element at index 0.
	at kotlin.collections.EmptyList.get(Collections.kt:36)
	at kotlin.collections.EmptyList.get(Collections.kt:24)
	at io.outfoxx.swiftpoet.CodeWriter.emitTypeVariables(CodeWriter.kt:159)
	at io.outfoxx.swiftpoet.FunctionSpec.emitSignature(FunctionSpec.kt:115)
	at io.outfoxx.swiftpoet.FunctionSpec.emit$swiftpoet(FunctionSpec.kt:62)
	at io.outfoxx.swiftpoet.FunctionSpec.emit$swiftpoet$default(FunctionSpec.kt:42)
	at io.outfoxx.swiftpoet.ExtensionSpec.emit$swiftpoet(ExtensionSpec.kt:95)
	at io.outfoxx.swiftpoet.FileMemberSpec.emit$swiftpoet(FileMemberSpec.kt:41)
	at io.outfoxx.swiftpoet.FileSpec.emit(FileSpec.kt:96)
	at io.outfoxx.swiftpoet.FileSpec.writeTo(FileSpec.kt:52)
	at io.outfoxx.swiftpoet.FileSpec.writeTo(FileSpec.kt:68)
	at io.outfoxx.swiftpoet.FileSpec.writeTo(FileSpec.kt:73)
```

**Comment by kdubb** [comment]
PR# #66 fixes this.

Tests for all the complex cases were present or recently added. A test for the very simplest case was missing 🤦‍♂️.
